// <auto-generated />
using System;
using ActionKids;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActionKids.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250319193135_ServiceStop")]
    partial class ServiceStop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ActionKids.Models.Kid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLostStars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Kids");
                });

            modelBuilder.Entity("ActionKids.Models.KidServiceRecord", b =>
                {
                    b.Property<int>("KidId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("KidId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("KidServiceRecords");
                });

            modelBuilder.Entity("ActionKids.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ServiceStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServiceStop")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ActionKids.Models.KidServiceRecord", b =>
                {
                    b.HasOne("ActionKids.Models.Kid", "Kid")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("KidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ActionKids.Models.Service", "Service")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kid");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ActionKids.Models.Kid", b =>
                {
                    b.Navigation("ServiceRecords");
                });

            modelBuilder.Entity("ActionKids.Models.Service", b =>
                {
                    b.Navigation("ServiceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
